name: main branch auto ci process script - 메인 브랜치로 CI/CD 하는 스크립트

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: SSH Private Key 사용하기 위해 .pem 파일 만들기
        env:
          SSH_PRIVATE_KEY: ${{secrets.REMOTE_SECRET_KEY}}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem 

      - name: remote ssh 명령 실행
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: private_key.pem # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ec2-user/Programmers_TeamRepo
            git pull origin main
            pm2 kill
            npm i --legacy-peer-deps  
            npm run build
            pm2 start dist/main.js